<?php
require_once(dirname(__FILE__).'/adstxt/module.php');
require_once(dirname(__FILE__).'/inpostads/module.php');
require_once(dirname(__FILE__).'/adwidgets/module.php');
require_once(dirname(__FILE__).'/shortcodeads/module.php');
require_once(dirname(__FILE__).'/inthemeads/module.php');
require_once(dirname(__FILE__).'/pagelevelads/module.php');
require_once(dirname(__FILE__).'/trackingcodes/module.php');
require_once(dirname(__FILE__).'/legalpages/module.php');
require_once(dirname(__FILE__).'/videointelligence/module.php');
?>