<?php
/*
* This template controlls the portfolio single entries: 
* These entries are generated by this file in conjunction with includes/loop-portfolio-single.php
*/

global $avia_config;

/*
* check which page template should be applied: 
* cecks for dynamic pages as well as for portfolio, fullwidth, blog, contact and any other possibility :)
* Be aware that if a match was found another template wil be included and the code bellow will not be executed
* located at the bottom of includes/helper-template-logic.php
*/
do_action('avia_action_template_check', 'single-portfolio');


/*
* get_header is a basic wordpress function, used to retrieve the header.php file in your theme directory.
*/
get_header();

?>
		
		<!-- ####### MAIN CONTAINER ####### -->
		<div class='container_wrap fullwidth single-portfolio-entry' id='main'>
		
			<div class='container'>
								
				<?php
//display link to previeous and next portfolio entry
echo avia_post_nav();

/* Run the loop to output the posts.
* If you want to overload this in a child theme then include a file
* called loop-page.php and that will be used instead.
*/
get_template_part('includes/loop', 'portfolio-single');


//show related posts based on categories if there are any
get_template_part('includes/related-posts');
?>
				<div class="navigation-prev-next"><?php


$cur_terms = get_the_terms($post->ID, 'portfolio_entries');
foreach ($cur_terms as $cur_term) {
    if ($cur_term->slug == 'obektyi') {
        previous_post_link('%link', 'Предыдущая статья из категории', true, '',
            'portfolio_entries');
        next_post_link('%link', 'Следующая статья из категории', true, '',
            'portfolio_entries');
    }

}



?></div>


<!--div class="footer-block">
<div class="title"><p>Свяжитесь с нами - и мы ответим на любой интересующий вас вопрос!</p></div>
<div class="one_third first"><p style="line-height:15px;">Пишите на почту - будем рады ответить <br /><strong>Наша почта:</strong> <a href="mailto:info@metallgarant-spb.ru">info@metallgarant-spb.ru</a><br />
<a href="#letter_form_pop" id="link_order" class="fancybox-inline" style="margin:10px;" onclick="return false"><img src="<?php bloginfo('template_url') ?>/images/letter.png" style="margin: 0 10px;"/> Написать письмо</a>
 <div style="display:none" class="fancybox-hidden">
 <div id="letter_form_pop">                
  <?php echo do_shortcode('[contact-form-7 id="3903" title="Написать письмо"]'); ?>
 </div>
 </div>
</p></div>
<div class="one_third"><img src="<?php bloginfo('template_url') ?>/images/phone-transparency.png" style="float:left;margin:5px 10px 0 0px;"/><p>Звонок по России <strong>бесплатный</strong><br /><span class="ya-phone-5">8 (812) 660-55-00</span><br /> <strong>КРУГЛОСУТОЧНО 24/7/365</strong></p></div>
<div class="one_third"><img src="<?php bloginfo('template_url') ?>/images/phone-callback.png" style="float:right;margin:5px 0 0 5px;"/><p style="line-height:15px;text-align:center;">Оставьте заявку - мы перезвоним <br /> в любое удобное для вас время<br /><a href="#contact_form_pop" class="fancybox-inline" onclick="return false">Заказать звонок</a></p> </div></div-->

			</div><!--end container-->

	</div>
	<!-- ####### END MAIN CONTAINER ####### -->


<?php get_footer(); ?>